- type: E-commerce / Educational
  name: Patrick Teaching Art
  list: PHP, Wordpress, jQuery
  picture: http://via.placeholder.com/650x250

- type: E-commerce / Educational
  name: Patrick Teaching Art
  list: PHP, Wordpress, jQuery
  picture: http://via.placeholder.com/650x250